// <auto-generated />
using System;
using Eswmp.Work.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Eswmp.Work.Data.Migrations
{
    [DbContext(typeof(WorkDbContext))]
    [Migration("20260724040039_AddDemandV2Delta")]
    partial class AddDemandV2Delta
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Eswmp.Work.Models.BufferRequirement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AppliesToRole")
                        .HasColumnType("text");

                    b.Property<int>("BufferType")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("integer");

                    b.Property<bool>("HardConstraint")
                        .HasColumnType("boolean");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<Guid>("WorkRequirementId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorkRequirementId");

                    b.ToTable("BufferRequirements", "requirement", t =>
                        {
                            t.HasCheckConstraint("CK_Buf_Positive", "\"DurationMinutes\" > 0");
                        });
                });

            modelBuilder.Entity("Eswmp.Work.Models.CapabilityRequirement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CapabilityCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Level")
                        .HasColumnType("text");

                    b.Property<bool>("Mandatory")
                        .HasColumnType("boolean");

                    b.Property<int?>("MinimumExperience")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ResourceRoleRequirementId")
                        .HasColumnType("uuid");

                    b.Property<string>("Scope")
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<Guid>("WorkRequirementId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ResourceRoleRequirementId");

                    b.HasIndex("WorkRequirementId");

                    b.ToTable("CapabilityRequirements", "requirement");
                });

            modelBuilder.Entity("Eswmp.Work.Models.CapacityRequirement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AggregationScope")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("DimensionCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Mandatory")
                        .HasColumnType("boolean");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric(18,4)");

                    b.Property<Guid?>("ResourceRoleRequirementId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Unit")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<Guid>("WorkRequirementId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ResourceRoleRequirementId");

                    b.HasIndex("WorkRequirementId");

                    b.ToTable("CapacityRequirements", "requirement", t =>
                        {
                            t.HasCheckConstraint("CK_CapaR_Quantity", "\"Quantity\" > 0");
                        });
                });

            modelBuilder.Entity("Eswmp.Work.Models.CertificationRequirement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CertificationTypeCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<bool>("Mandatory")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("MustBeValidThrough")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ResourceRoleRequirementId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<string>("VerificationLevel")
                        .HasColumnType("text");

                    b.Property<Guid>("WorkRequirementId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ResourceRoleRequirementId");

                    b.HasIndex("WorkRequirementId");

                    b.ToTable("CertificationRequirements", "requirement");
                });

            modelBuilder.Entity("Eswmp.Work.Models.DefinitionCapabilityRequirement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CapabilityCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<Guid>("DefinitionResourceRequirementId")
                        .HasColumnType("uuid");

                    b.Property<int>("Importance")
                        .HasColumnType("integer");

                    b.Property<int?>("MinimumLevel")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DefinitionResourceRequirementId");

                    b.ToTable("DefinitionCapabilityRequirements", "requirements");
                });

            modelBuilder.Entity("Eswmp.Work.Models.DefinitionCertificationRequirement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CertificationTypeCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<Guid>("DefinitionResourceRequirementId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Mandatory")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DefinitionResourceRequirementId");

                    b.ToTable("DefinitionCertificationRequirements", "requirements");
                });

            modelBuilder.Entity("Eswmp.Work.Models.DefinitionResourceRequirement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<bool>("Mandatory")
                        .HasColumnType("boolean");

                    b.Property<int>("MaximumQuantity")
                        .HasColumnType("integer");

                    b.Property<int>("MinimumQuantity")
                        .HasColumnType("integer");

                    b.Property<int>("PreferredQuantity")
                        .HasColumnType("integer");

                    b.Property<Guid>("RequirementDefinitionVersionId")
                        .HasColumnType("uuid");

                    b.Property<string>("ResourceTypeCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RequirementDefinitionVersionId");

                    b.ToTable("DefinitionResourceRequirements", "requirements");
                });

            modelBuilder.Entity("Eswmp.Work.Models.DefinitionSkillRequirement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<Guid>("DefinitionResourceRequirementId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Mandatory")
                        .HasColumnType("boolean");

                    b.Property<int?>("MinimumLevel")
                        .HasColumnType("integer");

                    b.Property<string>("SkillCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DefinitionResourceRequirementId");

                    b.ToTable("DefinitionSkillRequirements", "requirements");
                });

            modelBuilder.Entity("Eswmp.Work.Models.Demand", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("AssignedRole")
                        .HasColumnType("integer");

                    b.Property<string>("AssignedTo")
                        .HasColumnType("text");

                    b.Property<string>("AttentionIssuesJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("AttentionReason")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("DemandType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("ExternalReferenceId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ExternalReferenceType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("FulfillmentMode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("LastResolutionError")
                        .HasColumnType("text");

                    b.Property<string>("LocationReference")
                        .HasColumnType("jsonb");

                    b.Property<Guid?>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<string>("RecurrenceRule")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("RequestedEndAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("RequestedStartAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RequestedTimezone")
                        .HasColumnType("text");

                    b.Property<Guid?>("RequirementReferenceId")
                        .HasColumnType("uuid");

                    b.Property<int>("ResolutionAttempts")
                        .HasColumnType("integer");

                    b.Property<Guid?>("SeriesId")
                        .HasColumnType("uuid");

                    b.Property<string>("SourceChannel")
                        .HasColumnType("text");

                    b.Property<string>("SourceSystem")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Summary")
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "SeriesId")
                        .HasFilter("\"SeriesId\" IS NOT NULL");

                    b.HasIndex("TenantId", "AssignedRole", "CreatedAt")
                        .HasFilter("\"Status\" = 7");

                    b.HasIndex("TenantId", "ExternalReferenceType", "ExternalReferenceId");

                    b.HasIndex("TenantId", "Status", "CreatedAt");

                    b.ToTable("Demands", "demand", t =>
                        {
                            t.HasCheckConstraint("CK_Demands_Attempts", "\"ResolutionAttempts\" >= 0");

                            t.HasCheckConstraint("CK_Demands_AttentionReason", "\"Status\" <> 7 OR \"AttentionReason\" IS NOT NULL");

                            t.HasCheckConstraint("CK_Demands_Recurrence", "\"RecurrenceRule\" IS NULL OR \"FulfillmentMode\" = 2");

                            t.HasCheckConstraint("CK_Demands_TimeWindow", "\"RequestedStartAtUtc\" IS NULL OR \"RequestedEndAtUtc\" IS NULL OR \"RequestedStartAtUtc\" < \"RequestedEndAtUtc\"");
                        });
                });

            modelBuilder.Entity("Eswmp.Work.Models.DemandAuditEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActorId")
                        .HasColumnType("text");

                    b.Property<string>("ActorRole")
                        .HasColumnType("text");

                    b.Property<string>("AfterSummary")
                        .HasColumnType("jsonb");

                    b.Property<string>("BeforeSummary")
                        .HasColumnType("jsonb");

                    b.Property<string>("ChangeType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CorrelationId")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<Guid>("DemandId")
                        .HasColumnType("uuid");

                    b.Property<int?>("FromStatus")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<int?>("ToStatus")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DemandId");

                    b.HasIndex("TenantId", "DemandId", "OccurredAt");

                    b.ToTable("DemandAuditEntries", "demand");
                });

            modelBuilder.Entity("Eswmp.Work.Models.DemandIdempotencyRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<Guid>("DemandId")
                        .HasColumnType("uuid");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RequestHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ResponseBodyJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DemandId");

                    b.HasIndex("TenantId", "IdempotencyKey")
                        .IsUnique();

                    b.ToTable("DemandIdempotencyRecords", "demand");
                });

            modelBuilder.Entity("Eswmp.Work.Models.DemandLineage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActorId")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<Guid>("DemandId")
                        .HasColumnType("uuid");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.Property<Guid>("RelatedId")
                        .HasColumnType("uuid");

                    b.Property<int>("Relation")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DemandId");

                    b.HasIndex("RelatedId");

                    b.HasIndex("TenantId", "DemandId");

                    b.HasIndex("TenantId", "RelatedId");

                    b.ToTable("DemandLineage", "demand", t =>
                        {
                            t.HasCheckConstraint("CK_Lineage_NotSelf", "\"DemandId\" <> \"RelatedId\"");
                        });
                });

            modelBuilder.Entity("Eswmp.Work.Models.DemandValidationResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<Guid>("DemandId")
                        .HasColumnType("uuid");

                    b.Property<string>("IssuesJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("ValidatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DemandId");

                    b.HasIndex("TenantId", "DemandId", "ValidatedAt");

                    b.ToTable("DemandValidationResults", "demand");
                });

            modelBuilder.Entity("Eswmp.Work.Models.DependencyRequirement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("DependencyType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DependsOnReferenceId")
                        .HasColumnType("text");

                    b.Property<string>("DependsOnReferenceType")
                        .HasColumnType("text");

                    b.Property<bool>("HardConstraint")
                        .HasColumnType("boolean");

                    b.Property<int?>("LagMinutes")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<Guid>("WorkRequirementId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorkRequirementId");

                    b.ToTable("DependencyRequirements", "requirement");
                });

            modelBuilder.Entity("Eswmp.Work.Models.DurationRequirement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("CleanupDurationMinutes")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<int>("DurationType")
                        .HasColumnType("integer");

                    b.Property<int?>("EstimatedDurationMinutes")
                        .HasColumnType("integer");

                    b.Property<int?>("MaximumDurationMinutes")
                        .HasColumnType("integer");

                    b.Property<int?>("MinimumDurationMinutes")
                        .HasColumnType("integer");

                    b.Property<int?>("SetupDurationMinutes")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<Guid>("WorkRequirementId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorkRequirementId")
                        .IsUnique();

                    b.ToTable("DurationRequirements", "requirement", t =>
                        {
                            t.HasCheckConstraint("CK_Dur_Positive", "(\"EstimatedDurationMinutes\" IS NULL OR \"EstimatedDurationMinutes\" > 0) AND (\"MinimumDurationMinutes\" IS NULL OR \"MinimumDurationMinutes\" > 0) AND (\"MaximumDurationMinutes\" IS NULL OR \"MaximumDurationMinutes\" > 0) AND (\"MinimumDurationMinutes\" IS NULL OR \"MaximumDurationMinutes\" IS NULL OR \"MinimumDurationMinutes\" <= \"MaximumDurationMinutes\")");
                        });
                });

            modelBuilder.Entity("Eswmp.Work.Models.ExecutionRequirement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<int>("ExecutionMode")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<Guid>("WorkRequirementId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorkRequirementId")
                        .IsUnique();

                    b.ToTable("ExecutionRequirements", "requirement");
                });

            modelBuilder.Entity("Eswmp.Work.Models.LocationConstraint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<decimal?>("MaximumTravelDistanceKm")
                        .HasColumnType("numeric");

                    b.Property<int?>("MaximumTravelTimeMinutes")
                        .HasColumnType("integer");

                    b.Property<int>("Mode")
                        .HasColumnType("integer");

                    b.Property<Guid>("RequirementDefinitionVersionId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RequirementDefinitionVersionId");

                    b.ToTable("LocationConstraints", "requirements");
                });

            modelBuilder.Entity("Eswmp.Work.Models.LocationRequirement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("numeric(9,6)");

                    b.Property<string>("LocationFlexibility")
                        .HasColumnType("text");

                    b.Property<int>("LocationMode")
                        .HasColumnType("integer");

                    b.Property<string>("LocationReferenceId")
                        .HasColumnType("text");

                    b.Property<string>("LocationReferenceType")
                        .HasColumnType("text");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("numeric(9,6)");

                    b.Property<decimal?>("ServiceRadius")
                        .HasColumnType("numeric(10,2)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<Guid>("WorkRequirementId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorkRequirementId")
                        .IsUnique();

                    b.ToTable("LocationRequirements", "requirement");
                });

            modelBuilder.Entity("Eswmp.Work.Models.RequirementConstraint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConstraintType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<bool>("HardConstraint")
                        .HasColumnType("boolean");

                    b.Property<string>("Operator")
                        .HasColumnType("text");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.Property<string>("Scope")
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.Property<Guid>("WorkRequirementId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorkRequirementId");

                    b.ToTable("Constraints", "requirement");
                });

            modelBuilder.Entity("Eswmp.Work.Models.RequirementDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("ActiveVersionNumber")
                        .HasColumnType("integer");

                    b.Property<string>("Category")
                        .HasColumnType("text");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ConcurrencyVersion")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<int>("CurrentVersionNumber")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Code")
                        .IsUnique();

                    b.ToTable("RequirementDefinitions", "requirements");
                });

            modelBuilder.Entity("Eswmp.Work.Models.RequirementDefinitionSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("DefinitionJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.Property<Guid>("SourceRequirementId")
                        .HasColumnType("uuid");

                    b.Property<int>("SourceVersionNumber")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("RequirementDefinitionSnapshots", "requirements");
                });

            modelBuilder.Entity("Eswmp.Work.Models.RequirementDefinitionVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ChangeSummary")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<int>("DurationType")
                        .HasColumnType("integer");

                    b.Property<DateOnly?>("EffectiveFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("EffectiveTo")
                        .HasColumnType("date");

                    b.Property<int?>("ExpectedDurationMinutes")
                        .HasColumnType("integer");

                    b.Property<int?>("FixedDurationMinutes")
                        .HasColumnType("integer");

                    b.Property<int?>("MaximumDurationMinutes")
                        .HasColumnType("integer");

                    b.Property<int?>("MinimumDurationMinutes")
                        .HasColumnType("integer");

                    b.Property<int>("PostWorkBufferMinutes")
                        .HasColumnType("integer");

                    b.Property<int>("PreWorkBufferMinutes")
                        .HasColumnType("integer");

                    b.Property<Guid>("RequirementDefinitionId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RequirementDefinitionId");

                    b.HasIndex("TenantId", "VersionNumber", "RequirementDefinitionId")
                        .IsUnique();

                    b.ToTable("RequirementDefinitionVersions", "requirements");
                });

            modelBuilder.Entity("Eswmp.Work.Models.RequirementLineVisibility", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<bool>("CustomerVisible")
                        .HasColumnType("boolean");

                    b.Property<Guid>("LineId")
                        .HasColumnType("uuid");

                    b.Property<string>("LineType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<int>("VisibilityLevel")
                        .HasColumnType("integer");

                    b.Property<Guid>("WorkRequirementId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorkRequirementId");

                    b.HasIndex("LineType", "LineId")
                        .IsUnique();

                    b.HasIndex("TenantId", "WorkRequirementId", "VisibilityLevel");

                    b.ToTable("RequirementLineVisibility", "requirement", t =>
                        {
                            t.HasCheckConstraint("CK_RLV_Consistent", "\"CustomerVisible\" = false OR \"VisibilityLevel\" = 0");
                        });
                });

            modelBuilder.Entity("Eswmp.Work.Models.RequirementPreference", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("PreferenceType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Source")
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.Property<decimal?>("Weight")
                        .HasColumnType("numeric(5,2)");

                    b.Property<Guid>("WorkRequirementId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorkRequirementId");

                    b.ToTable("Preferences", "requirement");
                });

            modelBuilder.Entity("Eswmp.Work.Models.RequirementTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<int>("CurrentVersion")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<string>("WorkType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Code")
                        .IsUnique();

                    b.HasIndex("TenantId", "WorkType", "Status");

                    b.ToTable("RequirementTemplates", "requirement");
                });

            modelBuilder.Entity("Eswmp.Work.Models.RequirementTemplateVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ChangeReason")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("DefinitionJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset?>("EffectiveFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("EffectiveTo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("RowVersion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L);

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("TemplateId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TemplateId", "Version")
                        .IsUnique();

                    b.ToTable("RequirementTemplateVersions", "requirement");
                });

            modelBuilder.Entity("Eswmp.Work.Models.RequirementVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ChangeReason")
                        .HasColumnType("text");

                    b.Property<string>("ChangeType")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("SnapshotJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int?>("SourceVersion")
                        .HasColumnType("integer");

                    b.Property<int?>("TemplateVersion")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.Property<Guid>("WorkRequirementId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorkRequirementId", "Version")
                        .IsUnique();

                    b.ToTable("RequirementVersions", "requirement");
                });

            modelBuilder.Entity("Eswmp.Work.Models.ResourceRoleRequirement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<int?>("MaximumQuantity")
                        .HasColumnType("integer");

                    b.Property<int>("MinimumQuantity")
                        .HasColumnType("integer");

                    b.Property<bool>("Required")
                        .HasColumnType("boolean");

                    b.Property<int>("ResourceCategory")
                        .HasColumnType("integer");

                    b.Property<string>("RoleCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("SameResourceRequired")
                        .HasColumnType("boolean");

                    b.Property<int>("SelectionMode")
                        .HasColumnType("integer");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<Guid>("WorkRequirementId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorkRequirementId");

                    b.ToTable("ResourceRoleRequirements", "requirement", t =>
                        {
                            t.HasCheckConstraint("CK_RRR_Quantity", "\"MinimumQuantity\" > 0 AND (\"MaximumQuantity\" IS NULL OR \"MaximumQuantity\" >= \"MinimumQuantity\")");
                        });
                });

            modelBuilder.Entity("Eswmp.Work.Models.TimeRequirement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("Deadline")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("EarliestFinish")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("EarliestStart")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("FixedEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("FixedStart")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LatestFinish")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LatestStart")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<int>("TimeConstraintType")
                        .HasColumnType("integer");

                    b.Property<string>("Timezone")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<Guid>("WorkRequirementId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorkRequirementId")
                        .IsUnique();

                    b.ToTable("TimeRequirements", "requirement", t =>
                        {
                            t.HasCheckConstraint("CK_Time_Ordering", "(\"EarliestStart\" IS NULL OR \"LatestStart\" IS NULL OR \"EarliestStart\" <= \"LatestStart\") AND (\"FixedStart\" IS NULL OR \"FixedEnd\" IS NULL OR \"FixedStart\" < \"FixedEnd\") AND (\"EarliestStart\" IS NULL OR \"Deadline\" IS NULL OR \"EarliestStart\" <= \"Deadline\") AND (\"EarliestStart\" IS NULL OR \"LatestFinish\" IS NULL OR \"EarliestStart\" < \"LatestFinish\")");
                        });
                });

            modelBuilder.Entity("Eswmp.Work.Models.TravelRequirement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("DestinationMode")
                        .HasColumnType("text");

                    b.Property<decimal?>("MaximumTravelDistance")
                        .HasColumnType("numeric(10,2)");

                    b.Property<int?>("MaximumTravelTimeMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("OriginMode")
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<bool>("TravelRequired")
                        .HasColumnType("boolean");

                    b.Property<bool>("TravelTimeIncludedInWork")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<Guid>("WorkRequirementId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorkRequirementId")
                        .IsUnique();

                    b.ToTable("TravelRequirements", "requirement");
                });

            modelBuilder.Entity("Eswmp.Work.Models.WorkRequirement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ComplexityLevel")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("EffectiveFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("EffectiveTo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<int>("RequirementVersion")
                        .HasColumnType("integer");

                    b.Property<string>("ServiceMode")
                        .HasColumnType("text");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("SourceVersion")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid?>("TemplateId")
                        .HasColumnType("uuid");

                    b.Property<int?>("TemplateVersion")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<string>("WorkCategory")
                        .HasColumnType("text");

                    b.Property<string>("WorkType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TemplateId");

                    b.HasIndex("TenantId", "SourceType", "SourceId");

                    b.HasIndex("TenantId", "Status", "CreatedAt");

                    b.ToTable("WorkRequirements", "requirement");
                });

            modelBuilder.Entity("Eswmp.Work.Models.WorkRequirementIdempotencyRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RequestHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ResourceId")
                        .HasColumnType("uuid");

                    b.Property<string>("ResponseBodyJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "IdempotencyKey")
                        .IsUnique();

                    b.ToTable("IdempotencyRecords", "requirement");
                });

            modelBuilder.Entity("Eswmp.Work.Models.WorkRequirementOutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AggregateId")
                        .HasColumnType("uuid");

                    b.Property<string>("AggregateType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CorrelationId")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("OccurredAt")
                        .HasFilter("\"ProcessedAt\" IS NULL");

                    b.ToTable("OutboxMessages", "requirement");
                });

            modelBuilder.Entity("Eswmp.Work.Models.BufferRequirement", b =>
                {
                    b.HasOne("Eswmp.Work.Models.WorkRequirement", null)
                        .WithMany("BufferRequirements")
                        .HasForeignKey("WorkRequirementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Eswmp.Work.Models.CapabilityRequirement", b =>
                {
                    b.HasOne("Eswmp.Work.Models.ResourceRoleRequirement", null)
                        .WithMany()
                        .HasForeignKey("ResourceRoleRequirementId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Eswmp.Work.Models.WorkRequirement", null)
                        .WithMany("CapabilityRequirements")
                        .HasForeignKey("WorkRequirementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Eswmp.Work.Models.CapacityRequirement", b =>
                {
                    b.HasOne("Eswmp.Work.Models.ResourceRoleRequirement", null)
                        .WithMany()
                        .HasForeignKey("ResourceRoleRequirementId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Eswmp.Work.Models.WorkRequirement", null)
                        .WithMany("CapacityRequirements")
                        .HasForeignKey("WorkRequirementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Eswmp.Work.Models.CertificationRequirement", b =>
                {
                    b.HasOne("Eswmp.Work.Models.ResourceRoleRequirement", null)
                        .WithMany()
                        .HasForeignKey("ResourceRoleRequirementId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Eswmp.Work.Models.WorkRequirement", null)
                        .WithMany("CertificationRequirements")
                        .HasForeignKey("WorkRequirementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Eswmp.Work.Models.DefinitionCapabilityRequirement", b =>
                {
                    b.HasOne("Eswmp.Work.Models.DefinitionResourceRequirement", null)
                        .WithMany("CapabilityRequirements")
                        .HasForeignKey("DefinitionResourceRequirementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Eswmp.Work.Models.DefinitionCertificationRequirement", b =>
                {
                    b.HasOne("Eswmp.Work.Models.DefinitionResourceRequirement", null)
                        .WithMany("CertificationRequirements")
                        .HasForeignKey("DefinitionResourceRequirementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Eswmp.Work.Models.DefinitionResourceRequirement", b =>
                {
                    b.HasOne("Eswmp.Work.Models.RequirementDefinitionVersion", null)
                        .WithMany("ResourceRequirements")
                        .HasForeignKey("RequirementDefinitionVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Eswmp.Work.Models.DefinitionSkillRequirement", b =>
                {
                    b.HasOne("Eswmp.Work.Models.DefinitionResourceRequirement", null)
                        .WithMany("SkillRequirements")
                        .HasForeignKey("DefinitionResourceRequirementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Eswmp.Work.Models.DemandAuditEntry", b =>
                {
                    b.HasOne("Eswmp.Work.Models.Demand", null)
                        .WithMany()
                        .HasForeignKey("DemandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Eswmp.Work.Models.DemandIdempotencyRecord", b =>
                {
                    b.HasOne("Eswmp.Work.Models.Demand", null)
                        .WithMany()
                        .HasForeignKey("DemandId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Eswmp.Work.Models.DemandLineage", b =>
                {
                    b.HasOne("Eswmp.Work.Models.Demand", null)
                        .WithMany()
                        .HasForeignKey("DemandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Eswmp.Work.Models.Demand", null)
                        .WithMany()
                        .HasForeignKey("RelatedId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Eswmp.Work.Models.DemandValidationResult", b =>
                {
                    b.HasOne("Eswmp.Work.Models.Demand", null)
                        .WithMany()
                        .HasForeignKey("DemandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Eswmp.Work.Models.DependencyRequirement", b =>
                {
                    b.HasOne("Eswmp.Work.Models.WorkRequirement", null)
                        .WithMany("DependencyRequirements")
                        .HasForeignKey("WorkRequirementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Eswmp.Work.Models.DurationRequirement", b =>
                {
                    b.HasOne("Eswmp.Work.Models.WorkRequirement", null)
                        .WithOne("DurationRequirement")
                        .HasForeignKey("Eswmp.Work.Models.DurationRequirement", "WorkRequirementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Eswmp.Work.Models.ExecutionRequirement", b =>
                {
                    b.HasOne("Eswmp.Work.Models.WorkRequirement", null)
                        .WithOne("ExecutionRequirement")
                        .HasForeignKey("Eswmp.Work.Models.ExecutionRequirement", "WorkRequirementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Eswmp.Work.Models.LocationConstraint", b =>
                {
                    b.HasOne("Eswmp.Work.Models.RequirementDefinitionVersion", null)
                        .WithMany("LocationConstraints")
                        .HasForeignKey("RequirementDefinitionVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Eswmp.Work.Models.LocationRequirement", b =>
                {
                    b.HasOne("Eswmp.Work.Models.WorkRequirement", null)
                        .WithOne("LocationRequirement")
                        .HasForeignKey("Eswmp.Work.Models.LocationRequirement", "WorkRequirementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Eswmp.Work.Models.RequirementConstraint", b =>
                {
                    b.HasOne("Eswmp.Work.Models.WorkRequirement", null)
                        .WithMany("Constraints")
                        .HasForeignKey("WorkRequirementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Eswmp.Work.Models.RequirementDefinitionVersion", b =>
                {
                    b.HasOne("Eswmp.Work.Models.RequirementDefinition", null)
                        .WithMany("Versions")
                        .HasForeignKey("RequirementDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Eswmp.Work.Models.RequirementLineVisibility", b =>
                {
                    b.HasOne("Eswmp.Work.Models.WorkRequirement", null)
                        .WithMany("LineVisibilities")
                        .HasForeignKey("WorkRequirementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Eswmp.Work.Models.RequirementPreference", b =>
                {
                    b.HasOne("Eswmp.Work.Models.WorkRequirement", null)
                        .WithMany("Preferences")
                        .HasForeignKey("WorkRequirementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Eswmp.Work.Models.RequirementTemplateVersion", b =>
                {
                    b.HasOne("Eswmp.Work.Models.RequirementTemplate", null)
                        .WithMany("Versions")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Eswmp.Work.Models.RequirementVersion", b =>
                {
                    b.HasOne("Eswmp.Work.Models.WorkRequirement", null)
                        .WithMany()
                        .HasForeignKey("WorkRequirementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Eswmp.Work.Models.ResourceRoleRequirement", b =>
                {
                    b.HasOne("Eswmp.Work.Models.WorkRequirement", null)
                        .WithMany("ResourceRequirements")
                        .HasForeignKey("WorkRequirementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Eswmp.Work.Models.TimeRequirement", b =>
                {
                    b.HasOne("Eswmp.Work.Models.WorkRequirement", null)
                        .WithOne("TimeRequirement")
                        .HasForeignKey("Eswmp.Work.Models.TimeRequirement", "WorkRequirementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Eswmp.Work.Models.TravelRequirement", b =>
                {
                    b.HasOne("Eswmp.Work.Models.WorkRequirement", null)
                        .WithOne("TravelRequirement")
                        .HasForeignKey("Eswmp.Work.Models.TravelRequirement", "WorkRequirementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Eswmp.Work.Models.WorkRequirement", b =>
                {
                    b.HasOne("Eswmp.Work.Models.RequirementTemplate", null)
                        .WithMany()
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Eswmp.Work.Models.DefinitionResourceRequirement", b =>
                {
                    b.Navigation("CapabilityRequirements");

                    b.Navigation("CertificationRequirements");

                    b.Navigation("SkillRequirements");
                });

            modelBuilder.Entity("Eswmp.Work.Models.RequirementDefinition", b =>
                {
                    b.Navigation("Versions");
                });

            modelBuilder.Entity("Eswmp.Work.Models.RequirementDefinitionVersion", b =>
                {
                    b.Navigation("LocationConstraints");

                    b.Navigation("ResourceRequirements");
                });

            modelBuilder.Entity("Eswmp.Work.Models.RequirementTemplate", b =>
                {
                    b.Navigation("Versions");
                });

            modelBuilder.Entity("Eswmp.Work.Models.WorkRequirement", b =>
                {
                    b.Navigation("BufferRequirements");

                    b.Navigation("CapabilityRequirements");

                    b.Navigation("CapacityRequirements");

                    b.Navigation("CertificationRequirements");

                    b.Navigation("Constraints");

                    b.Navigation("DependencyRequirements");

                    b.Navigation("DurationRequirement");

                    b.Navigation("ExecutionRequirement");

                    b.Navigation("LineVisibilities");

                    b.Navigation("LocationRequirement");

                    b.Navigation("Preferences");

                    b.Navigation("ResourceRequirements");

                    b.Navigation("TimeRequirement");

                    b.Navigation("TravelRequirement");
                });
#pragma warning restore 612, 618
        }
    }
}
