// <auto-generated />
using System;
using Eswmp.Work.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Eswmp.Work.Data.Migrations
{
    [DbContext(typeof(WorkDbContext))]
    [Migration("20260717180728_RenameLegacyWorkRequirementModel")]
    partial class RenameLegacyWorkRequirementModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Eswmp.Work.Models.DefinitionCapabilityRequirement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CapabilityCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<Guid>("DefinitionResourceRequirementId")
                        .HasColumnType("uuid");

                    b.Property<int>("Importance")
                        .HasColumnType("integer");

                    b.Property<int?>("MinimumLevel")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DefinitionResourceRequirementId");

                    b.ToTable("DefinitionCapabilityRequirements", "requirements");
                });

            modelBuilder.Entity("Eswmp.Work.Models.DefinitionCertificationRequirement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CertificationTypeCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<Guid>("DefinitionResourceRequirementId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Mandatory")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DefinitionResourceRequirementId");

                    b.ToTable("DefinitionCertificationRequirements", "requirements");
                });

            modelBuilder.Entity("Eswmp.Work.Models.DefinitionResourceRequirement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<bool>("Mandatory")
                        .HasColumnType("boolean");

                    b.Property<int>("MaximumQuantity")
                        .HasColumnType("integer");

                    b.Property<int>("MinimumQuantity")
                        .HasColumnType("integer");

                    b.Property<int>("PreferredQuantity")
                        .HasColumnType("integer");

                    b.Property<Guid>("RequirementDefinitionVersionId")
                        .HasColumnType("uuid");

                    b.Property<string>("ResourceTypeCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RequirementDefinitionVersionId");

                    b.ToTable("DefinitionResourceRequirements", "requirements");
                });

            modelBuilder.Entity("Eswmp.Work.Models.DefinitionSkillRequirement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<Guid>("DefinitionResourceRequirementId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Mandatory")
                        .HasColumnType("boolean");

                    b.Property<int?>("MinimumLevel")
                        .HasColumnType("integer");

                    b.Property<string>("SkillCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DefinitionResourceRequirementId");

                    b.ToTable("DefinitionSkillRequirements", "requirements");
                });

            modelBuilder.Entity("Eswmp.Work.Models.Demand", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("DemandType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("ExternalReferenceId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ExternalReferenceType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("FulfillmentMode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("LocationReference")
                        .HasColumnType("jsonb");

                    b.Property<Guid?>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("RequestedEndAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("RequestedStartAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RequestedTimezone")
                        .HasColumnType("text");

                    b.Property<Guid?>("RequirementReferenceId")
                        .HasColumnType("uuid");

                    b.Property<string>("SourceChannel")
                        .HasColumnType("text");

                    b.Property<string>("SourceSystem")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Summary")
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "ExternalReferenceType", "ExternalReferenceId");

                    b.HasIndex("TenantId", "Status", "CreatedAt");

                    b.ToTable("Demands", "demand", t =>
                        {
                            t.HasCheckConstraint("CK_Demands_TimeWindow", "\"RequestedStartAtUtc\" IS NULL OR \"RequestedEndAtUtc\" IS NULL OR \"RequestedStartAtUtc\" < \"RequestedEndAtUtc\"");
                        });
                });

            modelBuilder.Entity("Eswmp.Work.Models.DemandIdempotencyRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<Guid>("DemandId")
                        .HasColumnType("uuid");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RequestHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ResponseBodyJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DemandId");

                    b.HasIndex("TenantId", "IdempotencyKey")
                        .IsUnique();

                    b.ToTable("DemandIdempotencyRecords", "demand");
                });

            modelBuilder.Entity("Eswmp.Work.Models.DemandValidationResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<Guid>("DemandId")
                        .HasColumnType("uuid");

                    b.Property<string>("IssuesJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("ValidatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DemandId");

                    b.HasIndex("TenantId", "DemandId", "ValidatedAt");

                    b.ToTable("DemandValidationResults", "demand");
                });

            modelBuilder.Entity("Eswmp.Work.Models.LocationConstraint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<decimal?>("MaximumTravelDistanceKm")
                        .HasColumnType("numeric");

                    b.Property<int?>("MaximumTravelTimeMinutes")
                        .HasColumnType("integer");

                    b.Property<int>("Mode")
                        .HasColumnType("integer");

                    b.Property<Guid>("RequirementDefinitionVersionId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RequirementDefinitionVersionId");

                    b.ToTable("LocationConstraints", "requirements");
                });

            modelBuilder.Entity("Eswmp.Work.Models.RequirementDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("ActiveVersionNumber")
                        .HasColumnType("integer");

                    b.Property<string>("Category")
                        .HasColumnType("text");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ConcurrencyVersion")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<int>("CurrentVersionNumber")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Code")
                        .IsUnique();

                    b.ToTable("RequirementDefinitions", "requirements");
                });

            modelBuilder.Entity("Eswmp.Work.Models.RequirementDefinitionSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("DefinitionJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.Property<Guid>("SourceRequirementId")
                        .HasColumnType("uuid");

                    b.Property<int>("SourceVersionNumber")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("RequirementDefinitionSnapshots", "requirements");
                });

            modelBuilder.Entity("Eswmp.Work.Models.RequirementDefinitionVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ChangeSummary")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<int>("DurationType")
                        .HasColumnType("integer");

                    b.Property<DateOnly?>("EffectiveFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("EffectiveTo")
                        .HasColumnType("date");

                    b.Property<int?>("ExpectedDurationMinutes")
                        .HasColumnType("integer");

                    b.Property<int?>("FixedDurationMinutes")
                        .HasColumnType("integer");

                    b.Property<int?>("MaximumDurationMinutes")
                        .HasColumnType("integer");

                    b.Property<int?>("MinimumDurationMinutes")
                        .HasColumnType("integer");

                    b.Property<int>("PostWorkBufferMinutes")
                        .HasColumnType("integer");

                    b.Property<int>("PreWorkBufferMinutes")
                        .HasColumnType("integer");

                    b.Property<Guid>("RequirementDefinitionId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RequirementDefinitionId");

                    b.HasIndex("TenantId", "VersionNumber", "RequirementDefinitionId")
                        .IsUnique();

                    b.ToTable("RequirementDefinitionVersions", "requirements");
                });

            modelBuilder.Entity("Eswmp.Work.Models.DefinitionCapabilityRequirement", b =>
                {
                    b.HasOne("Eswmp.Work.Models.DefinitionResourceRequirement", null)
                        .WithMany("CapabilityRequirements")
                        .HasForeignKey("DefinitionResourceRequirementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Eswmp.Work.Models.DefinitionCertificationRequirement", b =>
                {
                    b.HasOne("Eswmp.Work.Models.DefinitionResourceRequirement", null)
                        .WithMany("CertificationRequirements")
                        .HasForeignKey("DefinitionResourceRequirementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Eswmp.Work.Models.DefinitionResourceRequirement", b =>
                {
                    b.HasOne("Eswmp.Work.Models.RequirementDefinitionVersion", null)
                        .WithMany("ResourceRequirements")
                        .HasForeignKey("RequirementDefinitionVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Eswmp.Work.Models.DefinitionSkillRequirement", b =>
                {
                    b.HasOne("Eswmp.Work.Models.DefinitionResourceRequirement", null)
                        .WithMany("SkillRequirements")
                        .HasForeignKey("DefinitionResourceRequirementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Eswmp.Work.Models.DemandIdempotencyRecord", b =>
                {
                    b.HasOne("Eswmp.Work.Models.Demand", null)
                        .WithMany()
                        .HasForeignKey("DemandId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Eswmp.Work.Models.DemandValidationResult", b =>
                {
                    b.HasOne("Eswmp.Work.Models.Demand", null)
                        .WithMany()
                        .HasForeignKey("DemandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Eswmp.Work.Models.LocationConstraint", b =>
                {
                    b.HasOne("Eswmp.Work.Models.RequirementDefinitionVersion", null)
                        .WithMany("LocationConstraints")
                        .HasForeignKey("RequirementDefinitionVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Eswmp.Work.Models.RequirementDefinitionVersion", b =>
                {
                    b.HasOne("Eswmp.Work.Models.RequirementDefinition", null)
                        .WithMany("Versions")
                        .HasForeignKey("RequirementDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Eswmp.Work.Models.DefinitionResourceRequirement", b =>
                {
                    b.Navigation("CapabilityRequirements");

                    b.Navigation("CertificationRequirements");

                    b.Navigation("SkillRequirements");
                });

            modelBuilder.Entity("Eswmp.Work.Models.RequirementDefinition", b =>
                {
                    b.Navigation("Versions");
                });

            modelBuilder.Entity("Eswmp.Work.Models.RequirementDefinitionVersion", b =>
                {
                    b.Navigation("LocationConstraints");

                    b.Navigation("ResourceRequirements");
                });
#pragma warning restore 612, 618
        }
    }
}
